#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/mt6768-common

PRODUCT_COPY_FILES += \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/ILITEK_FW.hex:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/ILITEK_FW.hex \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/chipone_firmware.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/chipone_firmware.bin \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/chipone_limit.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/chipone_limit.bin \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/dijin_hdl_firmware.img:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/dijin_hdl_firmware.img \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/dijin_hdl_firmware_test.img:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/dijin_hdl_firmware_test.img \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/dijin_novatek_ts_fw.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/dijin_novatek_ts_fw.bin \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/dijin_novatek_ts_mp.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/dijin_novatek_ts_mp.bin \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/gt1151_default_firmware2.img:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt1151_default_firmware2.img \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/tianma_hdl_firmware.img:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/tianma_hdl_firmware.img \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/tianma_hdl_firmware_test.img:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/tianma_hdl_firmware_test.img \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/tianma_novatek_ts_fw.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/tianma_novatek_ts_fw.bin \
    vendor/motorola/mt6768-common/proprietary/recovery/root/vendor/firmware/tianma_novatek_ts_mp.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/tianma_novatek_ts_mp.bin \
    vendor/motorola/mt6768-common/proprietary/system/etc/public.libraries-mtk.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/public.libraries-mtk.txt \
    vendor/motorola/mt6768-common/proprietary/system_ext/etc/init/android.hardware.audio.parameter_parser.service.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/android.hardware.audio.parameter_parser.service.rc \
    vendor/motorola/mt6768-common/proprietary/system_ext/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.vtservice.rc \
    vendor/motorola/mt6768-common/proprietary/system_ext/etc/sysconfig/com.mediatek.ims.config.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/com.mediatek.ims.config.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.off.conf \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/apdb/APDB_MT6768_S01__W2438:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6768_S01__W2438 \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/apdb/APDB_MT6768_S01__W2438_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6768_S01__W2438_ENUM \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_DoCoMo.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_DoCoMo.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Peru.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Rakuten.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Rakuten.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gralloc/cam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/cam.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gralloc/dpu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/dpu.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gralloc/dpu_aeu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/dpu_aeu.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gralloc/gpu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/gpu.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/gralloc/vpu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/vpu.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init.insmod.mt6768.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.insmod.mt6768.cfg \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/android.hardware.audio.service-aidl.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.audio.service-aidl.mediatek.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint-service.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/android.hardware.gatekeeper-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service.trustonic.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/android.hardware.graphics.allocator-V2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator-V2-service-mediatek.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/android.hardware.graphics.composer@3.3-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.composer@3.3-service.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/android.hardware.media.c2-mediatek-64b.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2-mediatek-64b.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/android.hardware.security.keymint@3.0-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint@3.0-service.trustonic.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/android.hardware.tetheroffload-V1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.tetheroffload-V1-service.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/fingerprint-gf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fingerprint-gf.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.bip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.fmradio_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fmradio_drv.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.md_apps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.md_apps.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.vtservice_aidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_aidl.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.wfca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wfca.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.wmt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wmt_drv.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/init.wod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wod.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/ipsec_mon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipsec_mon.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/mtk_lbs_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_lbs_service.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/mtk_storageproxyd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_storageproxyd.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/v3avpud-64b.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/v3avpud-64b.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent-service.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms-service.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram-sevice.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq_aidl-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq_aidl-service.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/vendor.trustonic.tee-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee-service.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/mali_platform.config:$(TARGET_COPY_OUT_VENDOR)/etc/mali_platform.config \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/mtk_platform_codecs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_platform_codecs_config.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/motorola/mt6768-common/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/ILITEK_FW.hex:$(TARGET_COPY_OUT_VENDOR)/firmware/ILITEK_FW.hex \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/WIFI_RAM_CODE_soc1_0_1a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc1_0_1a_1.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/aw963xx_reg_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw963xx_reg_0.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/chipone_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/chipone_firmware.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/chipone_limit.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/chipone_limit.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/connfem.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/connfem.cfg \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/dijin_hdl_firmware.img:$(TARGET_COPY_OUT_VENDOR)/firmware/dijin_hdl_firmware.img \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/dijin_hdl_firmware_test.img:$(TARGET_COPY_OUT_VENDOR)/firmware/dijin_hdl_firmware_test.img \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/dijin_novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dijin_novatek_ts_fw.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/dijin_novatek_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dijin_novatek_ts_mp.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/fs1815.fsm:$(TARGET_COPY_OUT_VENDOR)/firmware/fs1815.fsm \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/gt1151_default_firmware2.img:$(TARGET_COPY_OUT_VENDOR)/firmware/gt1151_default_firmware2.img \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/soc1_0_patch_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_patch_mcu_1a_1_hdr.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/soc1_0_ram_bt_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_bt_1a_1_hdr.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/soc1_0_ram_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_mcu_1a_1_hdr.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/soc1_0_ram_wifi_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_wifi_1a_1_hdr.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/tianma_hdl_firmware.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tianma_hdl_firmware.img \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/tianma_hdl_firmware_test.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tianma_hdl_firmware_test.img \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/tianma_novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tianma_novatek_ts_fw.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/tianma_novatek_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tianma_novatek_ts_mp.bin \
    vendor/motorola/mt6768-common/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/motorola/mt6768-common/proprietary/vendor/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/libnfc-nxp_RF.conf

PRODUCT_PACKAGES += \
    av-audio-types-aidl-V3-ndk \
    android.hardware.audio.core-impl-mediatek \
    android.hardware.bluetooth.audio-impl-mediatek \
    arm.graphics-V5-ndk \
    arm.mali.platform-V2-ndk \
    libGLES_mali \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    android.hardware.audio.effect.aidl-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.graphics.allocator-V2-mediatek \
    android.hardware.soundtrigger3-impl \
    fingerprint.fpc.default \
    gf_fingerprint.default \
    gps.default \
    hwcomposer.mt6768 \
    mapper.mediatek \
    sensors.mt6768 \
    sound_trigger.primary.default \
    vendor.mediatek.hardware.audio-impl \
    vendor.mediatek.hardware.bluetooth.audio@2.1-impl \
    vendor.mediatek.hardware.gnss-impl \
    vendor.mediatek.hardware.nvram-impl \
    vendor.mediatek.hardware.pq_aidl-impl \
    vendor.mediatek.hardware.videotelephony-impl \
    vulkan.mali \
    libDR \
    libDefaultFpsActor \
    libFrameRecord \
    libHEVCdec_sa.ca7.android \
    libMcClient \
    libMtkSpeechEnh \
    libNoFpsActor \
    libQstAlgo \
    libTEECommon \
    lib_iir \
    libaal_cust \
    libaal_sec \
    libaalservice \
    libapmonitor_vendor \
    libapu_mdw \
    libarm_egl_properties_sysprop \
    libarm_gralloc_properties_sysprop \
    libarm_mali_config_sysprops \
    libaudio_aidl_conversion_common_ndk_prebuilt \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudiopolicyconfigxml_mtk_vendor \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_audio_session_aidl_mtk \
    libbluetooth_audio_session_mediatek \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libbwc \
    libcarrierconfig \
    libccci_util \
    libcodec2_fsr \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_vpp_fa_plugin \
    libcodec2_vpp_mi_plugin \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcurl_xcap_md \
    libcustom_nvram \
    libcvsd_mtk \
    libfgauge_gm30 \
    libfile_op \
    libforkexecwrap \
    libformatter \
    libfsmaudio \
    libged \
    libgf_ca \
    libgf_hal \
    libgoodixfingerprint \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgz_uree \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libhevce_sb.ca7.android \
    libhwm \
    libifcutils_mtk \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libmbrainSDKv \
    libmemsic \
    libmipc \
    libmmprofile \
    libmnetlink_v104 \
    libmnl \
    libmp4enc_sa.ca7 \
    libmsbc_mtk \
    libmtcloader \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtk_bsg \
    libmtk_drvb \
    libmtkconfig \
    libmtkconfigutils \
    libmtkcutils \
    libmtkhardware_legacy \
    libmtklimiter_vendor \
    libmtkmipc-ril \
    libmtknetcap \
    libmtknetutils \
    libmtkproperty \
    libmtkrillog \
    libmtkrilutils \
    libmtkshifter_vendor \
    libmtkspparser \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libmvpu_config_data \
    libmvpu_wrapper \
    libnvram \
    libnvram_sec \
    libnxp_extamp_intf \
    liboemcrypto \
    libpn560_fw \
    libpq_cust_base \
    libpqframework \
    libpqhdrmetaparser \
    libpqsharememory \
    libpqtuning \
    libpqxmlparser \
    libratconfig \
    librcs_volte_core \
    librilfusion \
    librt_extamp_intf \
    libsdrparser \
    libsensor_custom \
    libsilkybrightnesscore \
    libsimlock \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libstorage_otp \
    libswtcc \
    libsysenv \
    libthha \
    libtrm \
    liburee_meta_drmkeyinstall \
    libutinterface_custom_md \
    libutinterface_md \
    libvcodec_oal \
    libvcodec_utility_v3a \
    libvcodecdrv_v3a \
    libvendor.goodix.hardware.biometrics.fingerprint.cap \
    libverno \
    libvia-ril \
    libviamipc-ril \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    libvp8dec_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvpudv3a_vcodec \
    libwifi-hal-mtk \
    libwifinvram \
    libwifinvramdata \
    libwo \
    libwpfa \
    libdpframework \
    libmmagent \
    libmml \
    libmmlpqImpl \
    libpq_sec \
    libpqparamparser \
    mtk_lbs_service-impl \
    vendor.mediatek.hardware.apmonitor-V1-ndk \
    vendor.mediatek.hardware.apmonitor@2.0 \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.bluetooth.audio-V1-ndk \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    vendor.mediatek.hardware.clientapi-V1-ndk \
    vendor.mediatek.hardware.composer_ext-V1-ndk \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.gnss-V2-ndk \
    vendor.mediatek.hardware.lbs-V1-ndk \
    vendor.mediatek.hardware.lbs@1.0 \
    vendor.mediatek.hardware.mbrain-V6-ndk \
    vendor.mediatek.hardware.mmagent-V1-ndk \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mmlpq-V3-ndk \
    vendor.mediatek.hardware.mms-V1-ndk \
    vendor.mediatek.hardware.mtkpower-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.assist-V2-ndk \
    vendor.mediatek.hardware.mtkradioex.atci-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.cap-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.data-V3-ndk \
    vendor.mediatek.hardware.mtkradioex.dch-V2-ndk \
    vendor.mediatek.hardware.mtkradioex.em-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.ims-V2-ndk \
    vendor.mediatek.hardware.mtkradioex.messaging-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.modem-V3-ndk \
    vendor.mediatek.hardware.mtkradioex.mwi-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.network-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.rcs-V2-ndk \
    vendor.mediatek.hardware.mtkradioex.rsu-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.se-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.sim-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.sim-V2-ndk \
    vendor.mediatek.hardware.mtkradioex.smartratswitch-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.voice-V1-ndk \
    vendor.mediatek.hardware.netdagent-V1-ndk \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.nvram-V1-ndk \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq_aidl-V2-ndk \
    vendor.mediatek.hardware.pq_aidl-V4-ndk \
    vendor.mediatek.hardware.pq_aidl-V7-ndk \
    vendor.mediatek.hardware.rcs-V1-ndk \
    vendor.mediatek.hardware.rcs@2.0 \
    vendor.mediatek.hardware.videotelephony-V1-ndk_vendor \
    vendor.trustonic.tee-V1-ndk \
    vendor.trustonic.tui-V1-ndk \
    vpp_hdrmeta_handler_plugin \
    libapu_mdw_ext.mtk \
    libapuwareapusys.mtk \
    libapuwareapusys_v2.mtk \
    libapuwarehmp.mtk \
    libapuwareutils.mtk \
    libapuwareutils_v2.mtk \
    libapuwarexrp.mtk \
    libapuwarexrp_v2.mtk \
    libarmnn_ndk.mtk \
    libcmdl_ndk.mtk \
    libcomutils \
    libimsma \
    libimsma_adapt \
    libimsma_rtp \
    libimsma_socketwrapper \
    libmtk_vt_service \
    libmtk_vt_wrapper \
    libmvpu_cic_ci_compiler.mtk \
    libmvpu_cic_ci_compiler_25.mtk \
    libmvpu_clc_14_mvpu_debuginfo_25.mtk \
    libmvpu_clc_14_mvpu_elf_25.mtk \
    libmvpu_clc_14_mvpu_utility_25.mtk \
    libmvpu_clc_mvpu_debuginfo.mtk \
    libmvpu_clc_mvpu_elf.mtk \
    libmvpu_clc_mvpu_utility.mtk \
    libmvpu_config.mtk \
    libmvpu_engine.mtk \
    libmvpu_engine_25.mtk \
    libmvpu_engine_25_pub.mtk \
    libmvpu_engine_pub.mtk \
    libmvpu_pattern.mtk \
    libmvpu_pattern_25.mtk \
    libmvpu_pattern_25_pub.mtk \
    libmvpu_pattern_pub.mtk \
    libmvpu_runtime.mtk \
    libmvpu_runtime_25.mtk \
    libmvpu_runtime_25_pub.mtk \
    libmvpu_runtime_builtin.mtk \
    libmvpu_runtime_builtin_25.mtk \
    libmvpu_runtime_pub.mtk \
    libmvpuop25_mtk_cv.mtk \
    libmvpuop25_mtk_nn.mtk \
    libmvpuop_mtk_cv.mtk \
    libmvpuop_mtk_nn.mtk \
    libneuron_graph_delegate.mtk \
    libneuronusdk_adapter.mtk \
    libsignal \
    libsink-mtk \
    libsource \
    libtflite_mtk.mtk \
    libtflite_mtk \
    libvcodec_cap \
    libvcodec_capenc \
    libvt_avsync \
    vendor.mediatek.hardware.apuware.apusys-V5-ndk \
    vendor.mediatek.hardware.apuware.apusys@1.0 \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.apuware.utils-V1-ndk \
    vendor.mediatek.hardware.apuware.utils@1.0 \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.apuware.xrp-V1-ndk \
    vendor.mediatek.hardware.apuware.xrp@1.0 \
    vendor.mediatek.hardware.apuware.xrp@2.0 \
    vendor.mediatek.hardware.videotelephony-V1-ndk \
    vendor.mediatek.hardware.videotelephony@1.0 \
    com.google.android.widevine.nonupdatable \
    ImsService \
    MtkGbaService \
    MtkTelephonyAssist \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common \
    mediatek-ims-extension-plugin \
    android.hardware.audio.effect.service-aidl.xml \
    android.hardware.audio.service-aidl.mediatek.xml \
    android.hardware.biometrics.fingerprint-v3-service.xml \
    android.hardware.gatekeeper-service.trustonic.xml \
    android.hardware.security.keymint-service.trustonic.xml \
    android.hardware.security.secureclock-service.trustonic.xml \
    android.hardware.security.sharedsecret-service.trustonic.xml \
    android.hardware.tetheroffload-V1-service.xml \
    bluetooth_audio_mtk.xml \
    fingerprint-gf.xml \
    gnss-aosp-mtk.xml \
    gnss-mtk.xml \
    manifest_allocator.xml \
    manifest_com.fingerprints.fpc.extension@1.0-service.xml \
    manifest_hwcomposer.xml \
    manifest_media_c2_default.xml \
    mapper.mediatek.xml \
    mtk_lbs_service.xml \
    bip \
    ccci_mdinit \
    ccci_rpcd \
    epdg_wod \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.audio.service-aidl.mediatek \
    android.hardware.biometrics.fingerprint-service.example \
    android.hardware.biometrics.fingerprint-service.gf \
    android.hardware.gatekeeper-service.trustonic \
    android.hardware.gnss-service.mediatek \
    android.hardware.graphics.allocator-V2-service-mediatek \
    android.hardware.graphics.composer@3.3-service \
    android.hardware.media.c2-mediatek-64b \
    android.hardware.secure_element@1.2-service-mediatek \
    android.hardware.security.keymint@3.0-service.trustonic \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.mmagent-service \
    vendor.mediatek.hardware.mmlpq@V1-service \
    vendor.mediatek.hardware.mms-service \
    vendor.mediatek.hardware.nvram-service \
    vendor.mediatek.hardware.pq_aidl-service \
    vendor.trustonic.tee-service \
    vtservice_aidl \
    ipsec_mon \
    mcDriverDaemon \
    mnld \
    mtk_agpsd \
    mtk_lbs_service \
    mtk_storageproxyd \
    muxreport \
    nvram_daemon \
    v3avpud-64b \
    volte_clientapi_ua \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_rcs_ua \
    volte_stack \
    volte_ua \
    wfca \
    wmt_launcher \
    wmt_loader \
    android.hardware.audio.parameter_parser.service \
    vtservice

PRODUCT_PACKAGES += \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libmmagent_so \
    vendor_lib64_libmml_so \
    vendor_lib64_libmmlpqImpl_so \
    vendor_lib64_libpq_sec_so \
    vendor_lib64_libpqparamparser_so

PRODUCT_BOOT_JARS += \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common
